[package]
name = "termux-poller"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A low-resource periodic command runner for Termux"
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.bench]
inherits = "release"

[[bench]]
name = "core"
harness = false
